CREATE table auth_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mail VARCHAR(255),
    password VARCHAR(255),
    user_app_id BIGINT UNIQUE,

    CONSTRAINT fk_auth_user_user_app FOREIGN KEY (user_app_id) user_app(id) ON DELETE CASCADE
);